package model.services.client;

import model.services.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 02 13:12:50 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }


    public void createLineAction() {
        Object _ret =
            this.riInvokeExportedMethod(this,"createLineAction",null,null);
        return;
    }

    public void FillRollLines() {
        Object _ret = this.riInvokeExportedMethod(this,"FillRollLines",null,null);
        return;
    }

    public void setRollwhereClause() {
        Object _ret =
            this.riInvokeExportedMethod(this,"setRollwhereClause",null,null);
        return;
    }

    public void calcDet() {
        Object _ret = this.riInvokeExportedMethod(this,"calcDet",null,null);
        return;
    }

    public void makeBundles() {
        Object _ret = this.riInvokeExportedMethod(this,"makeBundles",null,null);
        return;
    }

    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSessionValues",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {orgId, userId, respId, respAppl});
        return;
    }

    public String callMatrix() {
        Object _ret = this.riInvokeExportedMethod(this,"callMatrix",null,null);
        return (String)_ret;
    }

    public void SplitBundles() {
        Object _ret = this.riInvokeExportedMethod(this,"SplitBundles",null,null);
        return;
    }

    public void save() {
        Object _ret = this.riInvokeExportedMethod(this,"save",null,null);
        return;
    }

    public void AvgConsumption_Calc() {
        Object _ret =
            this.riInvokeExportedMethod(this,"AvgConsumption_Calc",null,null);
        return;
    }

    public String Calculate_Cons(int HeaderId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"Calculate_Cons",new String [] {"int"},new Object[] {new Integer(HeaderId)});
        return (String)_ret;
    }
}
