package model.entities;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 22 15:00:26 BDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjCutlyrcntrlOffstandardDImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DetailId {
            public Object get(MnjCutlyrcntrlOffstandardDImpl obj) {
                return obj.getDetailId();
            }

            public void put(MnjCutlyrcntrlOffstandardDImpl obj, Object value) {
                obj.setDetailId((Number)value);
            }
        }
        ,
        SubDetailId {
            public Object get(MnjCutlyrcntrlOffstandardDImpl obj) {
                return obj.getSubDetailId();
            }

            public void put(MnjCutlyrcntrlOffstandardDImpl obj, Object value) {
                obj.setSubDetailId((Number)value);
            }
        }
        ,
        CodeStandard {
            public Object get(MnjCutlyrcntrlOffstandardDImpl obj) {
                return obj.getCodeStandard();
            }

            public void put(MnjCutlyrcntrlOffstandardDImpl obj, Object value) {
                obj.setCodeStandard((String)value);
            }
        }
        ,
        Descreption {
            public Object get(MnjCutlyrcntrlOffstandardDImpl obj) {
                return obj.getDescreption();
            }

            public void put(MnjCutlyrcntrlOffstandardDImpl obj, Object value) {
                obj.setDescreption((String)value);
            }
        }
        ,
        Area {
            public Object get(MnjCutlyrcntrlOffstandardDImpl obj) {
                return obj.getArea();
            }

            public void put(MnjCutlyrcntrlOffstandardDImpl obj, Object value) {
                obj.setArea((String)value);
            }
        }
        ,
        TotalStandad {
            public Object get(MnjCutlyrcntrlOffstandardDImpl obj) {
                return obj.getTotalStandad();
            }

            public void put(MnjCutlyrcntrlOffstandardDImpl obj, Object value) {
                obj.setTotalStandad((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(MnjCutlyrcntrlOffstandardDImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjCutlyrcntrlOffstandardDImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(MnjCutlyrcntrlOffstandardDImpl obj) {
                return obj.getAttribute3();
            }

            public void put(MnjCutlyrcntrlOffstandardDImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(MnjCutlyrcntrlOffstandardDImpl obj) {
                return obj.getAttribute4();
            }

            public void put(MnjCutlyrcntrlOffstandardDImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(MnjCutlyrcntrlOffstandardDImpl obj) {
                return obj.getAttribute5();
            }

            public void put(MnjCutlyrcntrlOffstandardDImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        MnjCutlyrcntrlOffstandardL {
            public Object get(MnjCutlyrcntrlOffstandardDImpl obj) {
                return obj.getMnjCutlyrcntrlOffstandardL();
            }

            public void put(MnjCutlyrcntrlOffstandardDImpl obj, Object value) {
                obj.setMnjCutlyrcntrlOffstandardL((MnjCutlyrcntrlOffstandardLImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjCutlyrcntrlOffstandardDImpl object);

        public abstract void put(MnjCutlyrcntrlOffstandardDImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int DETAILID = AttributesEnum.DetailId.index();
    public static final int SUBDETAILID = AttributesEnum.SubDetailId.index();
    public static final int CODESTANDARD = AttributesEnum.CodeStandard.index();
    public static final int DESCREPTION = AttributesEnum.Descreption.index();
    public static final int AREA = AttributesEnum.Area.index();
    public static final int TOTALSTANDAD = AttributesEnum.TotalStandad.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int MNJCUTLYRCNTRLOFFSTANDARDL = AttributesEnum.MnjCutlyrcntrlOffstandardL.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjCutlyrcntrlOffstandardDImpl() {
    }

    /**
     * Gets the attribute value for DetailId, using the alias name DetailId.
     * @return the DetailId
     */
    public Number getDetailId() {
        return (Number)getAttributeInternal(DETAILID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DetailId.
     * @param value value to set the DetailId
     */
    public void setDetailId(Number value) {
        setAttributeInternal(DETAILID, value);
    }

    /**
     * Gets the attribute value for SubDetailId, using the alias name SubDetailId.
     * @return the SubDetailId
     */
    public Number getSubDetailId() {
        return (Number)getAttributeInternal(SUBDETAILID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubDetailId.
     * @param value value to set the SubDetailId
     */
    public void setSubDetailId(Number value) {
        setAttributeInternal(SUBDETAILID, value);
    }

    /**
     * Gets the attribute value for CodeStandard, using the alias name CodeStandard.
     * @return the CodeStandard
     */
    public String getCodeStandard() {
        return (String)getAttributeInternal(CODESTANDARD);
    }

    /**
     * Sets <code>value</code> as the attribute value for CodeStandard.
     * @param value value to set the CodeStandard
     */
    public void setCodeStandard(String value) {
        setAttributeInternal(CODESTANDARD, value);
    }

    /**
     * Gets the attribute value for Descreption, using the alias name Descreption.
     * @return the Descreption
     */
    public String getDescreption() {
        return (String)getAttributeInternal(DESCREPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Descreption.
     * @param value value to set the Descreption
     */
    public void setDescreption(String value) {
        setAttributeInternal(DESCREPTION, value);
    }

    /**
     * Gets the attribute value for Area, using the alias name Area.
     * @return the Area
     */
    public String getArea() {
        return (String)getAttributeInternal(AREA);
    }

    /**
     * Sets <code>value</code> as the attribute value for Area.
     * @param value value to set the Area
     */
    public void setArea(String value) {
        setAttributeInternal(AREA, value);
    }

    /**
     * Gets the attribute value for TotalStandad, using the alias name TotalStandad.
     * @return the TotalStandad
     */
    public Number getTotalStandad() {
        return (Number)getAttributeInternal(TOTALSTANDAD);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalStandad.
     * @param value value to set the TotalStandad
     */
    public void setTotalStandad(Number value) {
        setAttributeInternal(TOTALSTANDAD, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity MnjCutlyrcntrlOffstandardLImpl.
     */
    public MnjCutlyrcntrlOffstandardLImpl getMnjCutlyrcntrlOffstandardL() {
        return (MnjCutlyrcntrlOffstandardLImpl)getAttributeInternal(MNJCUTLYRCNTRLOFFSTANDARDL);
    }

    /**
     * Sets <code>value</code> as the associated entity MnjCutlyrcntrlOffstandardLImpl.
     */
    public void setMnjCutlyrcntrlOffstandardL(MnjCutlyrcntrlOffstandardLImpl value) {
        setAttributeInternal(MNJCUTLYRCNTRLOFFSTANDARDL, value);
    }

    /**
     * @param subDetailId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number subDetailId) {
        return new Key(new Object[]{subDetailId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.entities.MnjCutlyrcntrlOffstandardD");
        }
        return mDefinitionObject;
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_CUTLYRCNTRL_OFFSTANDARD_DS",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setSubDetailId(sVal);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
