package model.entities;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 30 16:34:47 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjMfgCutlyrcntrlHImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        HeaderId {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getHeaderId();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        HeaderNo {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getHeaderNo();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setHeaderNo((String)value);
            }
        }
        ,
        TableNo {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getTableNo();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setTableNo((String)value);
            }
        }
        ,
        DocDate {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getDocDate();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setDocDate((Date)value);
            }
        }
        ,
        AddLayLength {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getAddLayLength();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setAddLayLength((String)value);
            }
        }
        ,
        RPlanNo {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getRPlanNo();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setRPlanNo((String)value);
            }
        }
        ,
        MinEndBit {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getMinEndBit();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setMinEndBit((Number)value);
            }
        }
        ,
        MinBunQty {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getMinBunQty();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setMinBunQty((Number)value);
            }
        }
        ,
        MaxBunQty {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getMaxBunQty();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setMaxBunQty((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getOrgId();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        Userid {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getUserid();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setUserid((Number)value);
            }
        }
        ,
        Respid {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getRespid();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setRespid((Number)value);
            }
        }
        ,
        Respapplid {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getRespapplid();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setRespapplid((Number)value);
            }
        }
        ,
        BuyerId {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getBuyerId();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        Style {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getStyle();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setStyle((String)value);
            }
        }
        ,
        Season {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getSeason();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        AvgActualConsumption {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getAvgActualConsumption();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setAvgActualConsumption((Number)value);
            }
        }
        ,
        PocId {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getPocId();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setPocId((Number)value);
            }
        }
        ,
        SystemId {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getSystemId();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setSystemId((Number)value);
            }
        }
        ,
        MnjMfgCutlyrcntrlL {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getMnjMfgCutlyrcntrlL();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjCutlyrcntrlWorkingpwrL {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getMnjCutlyrcntrlWorkingpwrL();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjCutlyrcntrlOffstandardL {
            public Object get(MnjMfgCutlyrcntrlHImpl obj) {
                return obj.getMnjCutlyrcntrlOffstandardL();
            }

            public void put(MnjMfgCutlyrcntrlHImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjMfgCutlyrcntrlHImpl object);

        public abstract void put(MnjMfgCutlyrcntrlHImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int HEADERNO = AttributesEnum.HeaderNo.index();
    public static final int TABLENO = AttributesEnum.TableNo.index();
    public static final int DOCDATE = AttributesEnum.DocDate.index();
    public static final int ADDLAYLENGTH = AttributesEnum.AddLayLength.index();
    public static final int RPLANNO = AttributesEnum.RPlanNo.index();
    public static final int MINENDBIT = AttributesEnum.MinEndBit.index();
    public static final int MINBUNQTY = AttributesEnum.MinBunQty.index();
    public static final int MAXBUNQTY = AttributesEnum.MaxBunQty.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int USERID = AttributesEnum.Userid.index();
    public static final int RESPID = AttributesEnum.Respid.index();
    public static final int RESPAPPLID = AttributesEnum.Respapplid.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int AVGACTUALCONSUMPTION = AttributesEnum.AvgActualConsumption.index();
    public static final int POCID = AttributesEnum.PocId.index();
    public static final int SYSTEMID = AttributesEnum.SystemId.index();
    public static final int MNJMFGCUTLYRCNTRLL = AttributesEnum.MnjMfgCutlyrcntrlL.index();
    public static final int MNJCUTLYRCNTRLWORKINGPWRL = AttributesEnum.MnjCutlyrcntrlWorkingpwrL.index();
    public static final int MNJCUTLYRCNTRLOFFSTANDARDL = AttributesEnum.MnjCutlyrcntrlOffstandardL.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjMfgCutlyrcntrlHImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.entities.MnjMfgCutlyrcntrlH");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for HeaderNo, using the alias name HeaderNo.
     * @return the HeaderNo
     */
    public String getHeaderNo() {
        return (String)getAttributeInternal(HEADERNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderNo.
     * @param value value to set the HeaderNo
     */
    public void setHeaderNo(String value) {
        setAttributeInternal(HEADERNO, value);
    }

    /**
     * Gets the attribute value for TableNo, using the alias name TableNo.
     * @return the TableNo
     */
    public String getTableNo() {
        return (String)getAttributeInternal(TABLENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for TableNo.
     * @param value value to set the TableNo
     */
    public void setTableNo(String value) {
        setAttributeInternal(TABLENO, value);
    }

    /**
     * Gets the attribute value for DocDate, using the alias name DocDate.
     * @return the DocDate
     */
    public Date getDocDate() {
        return (Date)getAttributeInternal(DOCDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocDate.
     * @param value value to set the DocDate
     */
    public void setDocDate(Date value) {
        setAttributeInternal(DOCDATE, value);
    }

    /**
     * Gets the attribute value for AddLayLength, using the alias name AddLayLength.
     * @return the AddLayLength
     */
    public String getAddLayLength() {
        return (String)getAttributeInternal(ADDLAYLENGTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for AddLayLength.
     * @param value value to set the AddLayLength
     */
    public void setAddLayLength(String value) {
        setAttributeInternal(ADDLAYLENGTH, value);
    }

    /**
     * Gets the attribute value for RPlanNo, using the alias name RPlanNo.
     * @return the RPlanNo
     */
    public String getRPlanNo() {
        return (String)getAttributeInternal(RPLANNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for RPlanNo.
     * @param value value to set the RPlanNo
     */
    public void setRPlanNo(String value) {
        setAttributeInternal(RPLANNO, value);
    }

    /**
     * Gets the attribute value for MinEndBit, using the alias name MinEndBit.
     * @return the MinEndBit
     */
    public Number getMinEndBit() {
        return (Number)getAttributeInternal(MINENDBIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for MinEndBit.
     * @param value value to set the MinEndBit
     */
    public void setMinEndBit(Number value) {
        setAttributeInternal(MINENDBIT, value);
    }

    /**
     * Gets the attribute value for MinBunQty, using the alias name MinBunQty.
     * @return the MinBunQty
     */
    public Number getMinBunQty() {
        return (Number)getAttributeInternal(MINBUNQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for MinBunQty.
     * @param value value to set the MinBunQty
     */
    public void setMinBunQty(Number value) {
        setAttributeInternal(MINBUNQTY, value);
    }

    /**
     * Gets the attribute value for MaxBunQty, using the alias name MaxBunQty.
     * @return the MaxBunQty
     */
    public Number getMaxBunQty() {
        return (Number)getAttributeInternal(MAXBUNQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for MaxBunQty.
     * @param value value to set the MaxBunQty
     */
    public void setMaxBunQty(Number value) {
        setAttributeInternal(MAXBUNQTY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for Userid, using the alias name Userid.
     * @return the Userid
     */
    public Number getUserid() {
        return (Number)getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Userid.
     * @param value value to set the Userid
     */
    public void setUserid(Number value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for Respid, using the alias name Respid.
     * @return the Respid
     */
    public Number getRespid() {
        return (Number)getAttributeInternal(RESPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Respid.
     * @param value value to set the Respid
     */
    public void setRespid(Number value) {
        setAttributeInternal(RESPID, value);
    }

    /**
     * Gets the attribute value for Respapplid, using the alias name Respapplid.
     * @return the Respapplid
     */
    public Number getRespapplid() {
        return (Number)getAttributeInternal(RESPAPPLID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Respapplid.
     * @param value value to set the Respapplid
     */
    public void setRespapplid(Number value) {
        setAttributeInternal(RESPAPPLID, value);
    }

    /**
     * Gets the attribute value for BuyerId, using the alias name BuyerId.
     * @return the BuyerId
     */
    public Number getBuyerId() {
        return (Number)getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuyerId.
     * @param value value to set the BuyerId
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for Style, using the alias name Style.
     * @return the Style
     */
    public String getStyle() {
        return (String)getAttributeInternal(STYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Style.
     * @param value value to set the Style
     */
    public void setStyle(String value) {
        setAttributeInternal(STYLE, value);
    }

    /**
     * Gets the attribute value for Season, using the alias name Season.
     * @return the Season
     */
    public String getSeason() {
        return (String)getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for Season.
     * @param value value to set the Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for AvgActualConsumption, using the alias name AvgActualConsumption.
     * @return the AvgActualConsumption
     */
    public Number getAvgActualConsumption() {
        return (Number)getAttributeInternal(AVGACTUALCONSUMPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for AvgActualConsumption.
     * @param value value to set the AvgActualConsumption
     */
    public void setAvgActualConsumption(Number value) {
        setAttributeInternal(AVGACTUALCONSUMPTION, value);
    }

    /**
     * Gets the attribute value for PocId, using the alias name PocId.
     * @return the PocId
     */
    public Number getPocId() {
        return (Number)getAttributeInternal(POCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PocId.
     * @param value value to set the PocId
     */
    public void setPocId(Number value) {
        setAttributeInternal(POCID, value);
    }

    /**
     * Gets the attribute value for SystemId, using the alias name SystemId.
     * @return the SystemId
     */
    public Number getSystemId() {
        return (Number)getAttributeInternal(SYSTEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SystemId.
     * @param value value to set the SystemId
     */
    public void setSystemId(Number value) {
        setAttributeInternal(SYSTEMID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjMfgCutlyrcntrlL() {
        return (RowIterator)getAttributeInternal(MNJMFGCUTLYRCNTRLL);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjCutlyrcntrlWorkingpwrL() {
        return (RowIterator)getAttributeInternal(MNJCUTLYRCNTRLWORKINGPWRL);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjCutlyrcntrlOffstandardL() {
        return (RowIterator)getAttributeInternal(MNJCUTLYRCNTRLOFFSTANDARDL);
    }


    /**
     * @param headerId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number headerId) {
        return new Key(new Object[]{headerId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =
            new oracle.jbo.server.SequenceImpl("MNJ_MFG_CUTLYRCNTRL_H_S",
                                               getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setHeaderId(sVal);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    
     protected void doDML(int operation, TransactionEvent e) {
             Map sessionScope = ADFContext.getCurrent().getSessionScope();   
             String user = (String)sessionScope.get("userId");
             String orgId  =(String)sessionScope.get("orgId");
             String unitName  =(String)sessionScope.get("unitName");
            
             System.out.println("Inquiry information DO DML 1 ------------------>"+user);
             System.out.println("Inquiry information DO DML 2------------------>"+orgId);
             System.out.println("Inquiry information DO DML 3 ------------------>"+unitName);
             
             if(DML_UPDATE == operation){
                       try {
                           setLastUpdatedDate((Date)Date.getCurrentDate()); 
                           setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                       } catch (SQLException f) {
                           System.out.println(f.getMessage());
                       }
             }
                   else if (DML_INSERT == operation){
                    
                       try {
                          
                           setOrgId(new oracle.jbo.domain.Number(orgId));
                           setHeaderNo(getSrNoString());
                           setCreationDate((Date)Date.getCurrentDate());  
                           setCreatedBy(new oracle.jbo.domain.Number(user));
                          
                          
                          
                       } catch (SQLException f) {
                           ;
                       }
                   }
             
             super.doDML(operation, e);
         }
    
    
    
    
//    protected void doDML(int operation, TransactionEvent e) {
//              
//        if (operation== DML_INSERT){
//            
//            setHeaderNo(getSrNoString());    
//        }
//        
//        super.doDML(operation, e);
//    }
    
    
    public String getSrNoString() {
          String srno = null;
          String stmt = "BEGIN :1 := mnj_mfg_doc_no_pkg.cut_layer_control; end;";
          java.sql.CallableStatement cs =   getDBTransaction().createCallableStatement(stmt, 1);
          try {
              cs.registerOutParameter(1, oracle.jdbc.OracleTypes.VARCHAR);
              cs.execute();
              srno = cs.getString(1);
              cs.close();
          } catch (Exception e) {
              e.printStackTrace();
          }
          return srno;
      }
}
