package model.services.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 02 13:12:50 BDT 2016
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void createLineAction();

    void FillRollLines();

    void setRollwhereClause();

    void calcDet();

    void makeBundles();

    void setSessionValues(String orgId, String userId, String respId,
                          String respAppl);

    String callMatrix();

    void SplitBundles();

    void save();

    void AvgConsumption_Calc();

    String Calculate_Cons(int HeaderId);
}
